random_seed:
sigma: 0.0
test_batch_size: 512
test_data_generating_distribution: uniform
test_misreport_inits: 100
test_misreport_iters: 1000
test_misreport_lr: 1e-1
test_num_examples: 10000
util_num_samples: 1